//! The three renderings: the summary a reviewer opens first, the obligations nobody may forget,
//! and the terminal form.
//!
//! Canonical like every other document in this family: same projection, same bytes, no clock and
//! no terminal width. `tests/determinism.rs` renders twice and compares.
//!
//! # Why two markdown files and not one
//!
//! `SUMMARY.md` answers *what does this tree do* — the counts, the provenance, one row per file.
//! `OBLIGATIONS.md` answers *what does this tree not do*, which is the part that gets lost. A
//! projection that emitted nine patches and quietly left six decisions unmade would read, in a
//! pull request, exactly like a projection that closed everything. Splitting them means the second
//! file is a diff of its own: it appears, it grows, it shrinks, and a reviewer sees which.

use std::fmt::Write as _;

use crate::project::{Disposition, GapOrigin, Projection};

/// One markdown table cell's text, with the one character a table cannot hold escaped.
///
/// A predicate is written `a >= 2 || b == 1` and a table row is written with pipes, so this is not
/// hypothetical: without the escape, one expectation's own vocabulary silently splits a row into
/// three columns.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

/// `SUMMARY.md`: what this tree changes, and what it was computed from.
///
/// One function rather than six, deliberately: the document is a sequence of sections in a fixed
/// order, and splitting it would scatter that order across six signatures without removing a line.
#[allow(clippy::too_many_lines)]
#[must_use]
pub fn summary_markdown(projection: &Projection) -> String {
    let summary = &projection.summary;
    let mut out = String::new();
    let _ = writeln!(out, "# Projection: {}\n", projection.specification);
    let _ = writeln!(
        out,
        "Generated by `protocol infra project`. **Nothing here has been applied.** Every file in \
         this tree is a change somebody has to read and decide to make.\n"
    );

    let _ = writeln!(out, "## Computed from\n");
    let _ = writeln!(out, "| input | digest |");
    let _ = writeln!(out, "| --- | --- |");
    let _ = writeln!(
        out,
        "| specification `{}` | `{}` |",
        projection.specification, projection.provenance.specification_digest
    );
    let _ = writeln!(
        out,
        "| snapshot of `{}` | `{}` |",
        projection.provenance.context, projection.provenance.snapshot_digest
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## What it does\n");
    let _ = writeln!(out, "| | count |");
    let _ = writeln!(out, "| --- | --- |");
    for (label, value) in [
        ("gaps in the snapshot", summary.gaps_observed),
        ("gaps these changes would open", summary.gaps_induced),
        ("closed by a generated change", summary.generated),
        ("owed as an obligation", summary.obligations),
        ("refused", summary.refusals),
        ("patch files", summary.patches),
        ("new objects", summary.objects),
    ] {
        let _ = writeln!(out, "| {label} | {value} |");
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Expectations before: **{} hold, {} gaps, {} undecidable**. After every file in this tree \
         is applied: **{} hold, {} gaps, {} undecidable**.\n",
        summary.verdicts_before.holds,
        summary.verdicts_before.gaps,
        summary.verdicts_before.undecidable,
        summary.verdicts_after.holds,
        summary.verdicts_after.gaps,
        summary.verdicts_after.undecidable
    );

    if projection.patches.is_empty() {
        let _ = writeln!(out, "## Patches\n\nNone.\n");
    } else {
        let _ = writeln!(out, "## Patches\n");
        let _ = writeln!(out, "| file | object | type | apply with |");
        let _ = writeln!(out, "| --- | --- | --- | --- |");
        for patch in &projection.patches {
            let _ = writeln!(
                out,
                "| [`{}`]({}) | `{}` | {} | `{}` |",
                patch.path,
                patch.path,
                patch.target,
                patch.patch_type,
                cell(&patch.target.kubectl_patch(patch.patch_type, &patch.path))
            );
        }
        let _ = writeln!(out);
    }

    if projection.objects.is_empty() {
        let _ = writeln!(out, "## New objects\n\nNone.\n");
    } else {
        let _ = writeln!(out, "## New objects\n");
        let _ = writeln!(out, "| file | object |");
        let _ = writeln!(out, "| --- | --- |");
        for object in &projection.objects {
            let _ = writeln!(
                out,
                "| [`{}`]({}) | `{}` |",
                object.path, object.path, object.target
            );
        }
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "## Every change, by the gap it closes\n");
    let generated: Vec<_> = projection
        .entries
        .iter()
        .filter_map(|entry| match &entry.disposition {
            Disposition::Generated(change) => Some((entry, change)),
            Disposition::Obligation(_) | Disposition::Refused(_) => None,
        })
        .collect();
    if generated.is_empty() {
        let _ = writeln!(out, "Nothing in this snapshot closes mechanically.\n");
    } else {
        let _ = writeln!(out, "| expectation | subject | gap | change | file |");
        let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
        for (entry, change) in generated {
            let _ = writeln!(
                out,
                "| `{}`{} | `{}` | {} | `{}` | [`{}`]({}) |",
                entry.expectation,
                induced_marker(entry.origin),
                entry.subject,
                cell(&entry.reads),
                cell(&change.change),
                change.artifact,
                change.artifact
            );
        }
        let _ = writeln!(out);
    }

    let owed = projection.owed().count();
    if owed == 0 {
        let _ = writeln!(
            out,
            "Every gap in this snapshot is closed by a file in this tree. See \
             [`OBLIGATIONS.md`](OBLIGATIONS.md), which says so."
        );
    } else {
        let _ = writeln!(
            out,
            "{owed} gap(s) are **not** closed by this tree. Read \
             [`OBLIGATIONS.md`](OBLIGATIONS.md) before treating it as complete."
        );
    }
    out
}

/// `OBLIGATIONS.md`: every gap that refused a mechanical patch, and why.
#[must_use]
pub fn obligations_markdown(projection: &Projection) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Obligations: {}\n", projection.specification);
    let _ = writeln!(
        out,
        "Every gap this projection did **not** write a change for, and the reason. Applying every \
         file in the tree beside this one leaves exactly these.\n"
    );
    let _ = writeln!(
        out,
        "Computed from specification `{}` against snapshot `{}` of `{}`.\n",
        projection.provenance.specification_digest,
        projection.provenance.snapshot_digest,
        projection.provenance.context
    );

    let obligations: Vec<_> = projection
        .entries
        .iter()
        .filter_map(|entry| match &entry.disposition {
            Disposition::Obligation(obligation) => Some((entry, obligation)),
            Disposition::Generated(_) | Disposition::Refused(_) => None,
        })
        .collect();
    let refusals: Vec<_> = projection
        .entries
        .iter()
        .filter_map(|entry| match &entry.disposition {
            Disposition::Refused(refusal) => Some((entry, refusal)),
            Disposition::Generated(_) | Disposition::Obligation(_) => None,
        })
        .collect();

    let _ = writeln!(out, "## Decisions owed ({})\n", obligations.len());
    if obligations.is_empty() {
        let _ = writeln!(out, "None.\n");
    } else {
        for (entry, obligation) in obligations {
            let _ = writeln!(
                out,
                "### `{}` — `{}`{}\n",
                entry.expectation,
                entry.subject,
                induced_marker(entry.origin)
            );
            let _ = writeln!(out, "* **observed:** {}", entry.reads);
            let _ = writeln!(
                out,
                "* **why not a patch:** {}",
                obligation.reason.describes()
            );
            let _ = writeln!(out, "* **decision:** {}\n", obligation.decision);
        }
    }

    let _ = writeln!(out, "## Refused ({})\n", refusals.len());
    if refusals.is_empty() {
        let _ = writeln!(
            out,
            "None. Every gap this tree does not close is one a person can close.\n"
        );
    } else {
        let _ = writeln!(
            out,
            "Gaps this build does not represent as a change at all, rather than approximating \
             one.\n"
        );
        for (entry, refusal) in refusals {
            let _ = writeln!(
                out,
                "### `{}` — `{}`{}\n",
                entry.expectation,
                entry.subject,
                induced_marker(entry.origin)
            );
            let _ = writeln!(out, "* **observed:** {}", entry.reads);
            let _ = writeln!(out, "* **class:** {}", refusal.reason.describes());
            let _ = writeln!(out, "* **detail:** {}\n", refusal.detail);
        }
    }
    out
}

/// One line per entry, then the counts — the terminal rendering.
#[must_use]
pub fn projection_to_text(projection: &Projection) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{} against {} ({})",
        projection.specification,
        projection.provenance.context,
        &projection.provenance.snapshot_digest[..12]
    );
    let _ = writeln!(
        out,
        "specification {}",
        &projection.provenance.specification_digest[..12]
    );
    let _ = writeln!(out);
    for entry in &projection.entries {
        let (marker, detail) = match &entry.disposition {
            Disposition::Generated(change) => ("gen", change.change.clone()),
            Disposition::Obligation(obligation) => ("owe", obligation.decision.clone()),
            Disposition::Refused(refusal) => ("ref", refusal.detail.clone()),
        };
        let _ = writeln!(
            out,
            "{marker} {} — {}{}",
            entry.expectation,
            entry.subject,
            induced_marker(entry.origin)
        );
        let _ = writeln!(out, "      {}", entry.reads);
        let _ = writeln!(out, "      {detail}");
    }
    let summary = &projection.summary;
    let _ = writeln!(out);
    for file in projection
        .patches
        .iter()
        .map(|patch| patch.path.as_str())
        .chain(projection.objects.iter().map(|object| object.path.as_str()))
    {
        let _ = writeln!(out, "  {file}");
    }
    if summary.patches + summary.objects > 0 {
        let _ = writeln!(out);
    }
    let _ = writeln!(
        out,
        "{} gap(s): {} generated, {} owed, {} refused; {} patch file(s), {} new object(s)",
        projection.entries.len(),
        summary.generated,
        summary.obligations,
        summary.refusals,
        summary.patches,
        summary.objects
    );
    let _ = writeln!(
        out,
        "expectations {} hold -> {} hold, {} gaps -> {} gaps",
        summary.verdicts_before.holds,
        summary.verdicts_after.holds,
        summary.verdicts_before.gaps,
        summary.verdicts_after.gaps
    );
    out
}

/// The mark an induced gap carries wherever it is named.
///
/// A footnote rather than a column, because it is the exception: most gaps are the cluster's, and
/// the ones this projection's own changes opened have to be visibly different or a reader will
/// read them as findings about the cluster.
fn induced_marker(origin: GapOrigin) -> &'static str {
    match origin {
        GapOrigin::Observed => "",
        GapOrigin::Induced => " (induced by this projection)",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn only_an_induced_gap_is_marked_so_a_reader_can_tell_it_from_the_clusters_own() {
        assert_eq!(induced_marker(GapOrigin::Observed), "");
        assert!(induced_marker(GapOrigin::Induced).contains("induced"));
    }
}
